FROM golang:1.18-alpine

ENV GO111MODULE=on \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o /monitor-api

EXPOSE 1234

CMD [ "/monitor-api" ]